#Makefile for running/cleaning scrapes

scrapes: IndeedAnalysts.tsv IndeedScientists.tsv IndeedMLs.tsv
	python3 Webscrape-IndeedDataAnls.py
	python3 Webscrape-IndeedDataScis.py
	Python3 Webscrape-IndeedMLs.py
